baseurl: /
languageCode: en-US
title: xiaohao yang | 楊瀟豪
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
      weight: 7
    - name: Posts
      url: /post/
      weight: 6
    - name: Research
      url: /research/
      weight: 4
    - name: Design
      url: /designworks/
      weight: 1
    - name: Tools
      url: /tools/
      weight: 5
    - name: Artwork
      url: /artworks/
      weight: 2
    - name: Games
      url: /games/
      weight: 3
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
taxonomies:
  tag: "tags"
